
spring:
  application:
    name: IPMPayment-paycenter-alipay

  datasource:
    url: jdbc:mysql://192.168.35.188:3306/pre?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ipanel
    initialSize: 5    # 初始化大小
    minIdle: 5        # 最小
    maxActive: 20     # 最大
    maxWait: 60000    # 获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000      # 配置一个连接在池中最小生存的时间，单位是毫秒

  redis:
    host: 192.168.35.188
    port: 6381
    password:
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 30000ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 1 # 连接池中的最小空闲连接
    timeout: 6000ms # 连接超时时间（毫秒）
    database: 1 # Redis数据库索引（默认为0）

mybatis:
  type-aliases-package: com.ipanel.partymember.pojo
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名转换
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
    config: classpath:logback-spring.xml
    path: D:/javaWorkplace/ideaWorkplace/partymemberInformationManagement/logs/partymembeManagement
    level:
      com.ipanel.partymember.mapper: debug

# JWT参数
jwt:
  header: Authorization
  # token头部
  tokenHead: Bearer
